service:
- service-name: foo-service
  owned-by: team#1
  criticality: non-critical
  git-repo: https://git-repo-foo
  deploy-on: ['staging','qa','prod']
  tech-leads:
    - Jaspin@gmail.com
  managers: Jaspin@gmail.com
- service-name: bar-service
  owned-by: team#2
  criticality: critical
  git-repo: https://git-repo-foo
  deploy-on: ['prod','staging','qa']
  tech-leads:
    - Brigham@gmail.com
    - Ranger@gmail.com
    - john@gmail.com
  managers: Ranger@gmail.com
- service-name: foo-bar-service
  owned-by: team#1
  criticality: critical
  git-repo: https://git-repo-foo
  deploy-on: ['prod','staging','qa']
  tech-leads:
    - john@gmail.com
    - Jaspin@gmail.com
  managers: Jaspin@gmail.com
- service-name: foo-service-v2
  owned-by: team#1
  criticality: critical
  git-repo: https://git-repo-foo
  deploy-on: ['prod','staging','qa']
  tech-leads:
    - Jaspin@gmail.com
  managers: Jaspin@gmail.com
- service-name: xyz-service
  owned-by: team#1
  criticality: critical
  git-repo: https://git-repo-foo
  deploy-on: ['prod','staging','qa']
  tech-leads:
    - john@gmail.com
    - Jaspin@gmail.com
  managers: Jaspin@gmail.com
- service-name: def-service
  owned-by: team#1
  criticality: critical
  git-repo: https://git-repo-foo
  deploy-on: ['staging','qa']
  tech-leads:
    - john@gmail.com
    - Jaspin@gmail.com
  managers: Jaspin@gmail.com
- service-name: abc-service
  owned-by: team#2
  criticality: critical
  git-repo: https://git-repo-foo
  deploy-on: ['staging','qa','prod']
  tech-leads:
    - Brigham@gmail.com
    - Ranger@gmail.com
  managers: Ranger@gmail.com

